# Generated by Django 4.2.2 on 2023-06-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pri0rity',
            new_name='priority',
        ),
    ]
