# Generated by Django 4.2.2 on 2023-07-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_pri0rity_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-01-22'),
            preserve_default=False,
        ),
    ]
